#
# Base system playbook
#
---
- name: Base Playbook
  hosts: all

- include: playbook.yml playbook=root tags=root
- include: playbook.yml playbook=motd tags=motd
- include: playbook.yml playbook=keys tags=keys
- include: playbook.yml playbook=ulimit tags=ulimit
- include: playbook.yml playbook=sysctl tags=sysctl
- include: playbook.yml playbook=yum tags=yum
- include: playbook.yml playbook=logrotate tags=logrotate
- include: playbook.yml playbook=iptables tags=iptables
- include: playbook.yml playbook=pam tags=pam
- include: playbook.yml playbook=ldap tags=ldap
- include: playbook.yml playbook=nscd tags=nscd
- include: playbook.yml playbook=nsswitch tags=nsswitch
- include: playbook.yml playbook=resolv tags=resolv
- include: playbook.yml playbook=ntp tags=ntp
- include: playbook.yml playbook=aliases tags=aliases
- include: playbook.yml playbook=profiled tags=profiled
- include: playbook.yml playbook=snmp tags=snmp
- include: playbook.yml playbook=monit tags=monit
- include: playbook.yml playbook=sudoers tags=sudoers
