#
#
#
---
- name: Base Playbook
  hosts: all

  vars_files:
  - vars/global.yml

- include: playbook.yml playbook=motd tags=motd
- include: playbook.yml playbook=keys tags=keys
- include: playbook.yml playbook=ulimit tags=ulimit
- include: playbook.yml playbook=sysctl tags=sysctl
- include: playbook.yml playbook=yum tags=yum
