#
#
#
---
- name: Base Playbook
  hosts: all

- include: playbook.yml playbook=root tags=root
- include: playbook.yml playbook=motd tags=motd
- include: playbook.yml playbook=keys tags=keys
- include: playbook.yml playbook=ulimit tags=ulimit
- include: playbook.yml playbook=sysctl tags=sysctl
- include: playbook.yml playbook=yum tags=yum
