#
# LAMP Stack Playbook
#
# TODO: document all tags that can be used in base and other playbooks
# ie. apache.cfg, mysql.cfg, mysql.init.root, mysql.init.db
#
---
- name: Lamp Playbook
  hosts: lamp

- include: base.yml tags=base
- include: playbook.yml playbook=httpd tags=httpd
- include: playbook.yml playbook=php tags=php
- include: playbook.yml playbook=mysql tags=mysql
