#
# Proxy playbook
#
---
- name: Proxy Playbook
  hosts: all

  vars:
    version: 1.0

  # see if we can git rid of this using group_vars/all
  vars_files:
  - vars/global.yml

  tasks:
#  - command: echo ${playbook_tasks}/${playbook}.yml
  - include: ${playbook_tasks}/${playbook}.yml

#  handlers:
  - include: ${playbook_handlers}/global.yml
