#
# ie. ansible-playbook playbooks/play.yml --extra-vars="host=all group=delegator-rebrand play=mysql" --tags="mysql.cfg"
#
---
- name: Dynamic Playbook
  hosts: ${host}

  vars:
    group: ${group}
 
- include: base.yml
- include: playbook.yml playbook=${play}
