#
# ie. ansible-playbook playbooks/play.yml --extra-vars="hosts=all group=delegator-rebrand play=mysql" --tags="mysql.cfg"
#
---
- name: Dynamic Playbook
  hosts: ${hosts}

  vars:
    group: ${group}
 
- include: base.yml
- include: playbook.yml playbook=${play}
