#
# LDAP 389 Directory Server Tasks
#
---
- yum: pkg=${item} state=installed
  with_items:
  - 389-ds
  - bind-utils
  tags:
  - ldap.pkgs

- copy: src=${item} dest=/etc/openldap/cacerts/cacert.pem owner=root group=root mode=0644
  first_available_file:
  - ${playbook_files_private}/${playbook}/cacert.pem-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/cacert.pem-${host_group}
  - ${playbook_files_private}/${playbook}/cacert.pem-${datacentre}
  - ${playbook_files_private}/${playbook}/cacert.pem
  - ${playbook_files}/${playbook}/cacert.pem-${ansible_fqdn}
  - ${playbook_files}/${playbook}/cacert.pem-${host_group}
  - ${playbook_files}/${playbook}/cacert.pem-${datacentre}
  - ${playbook_files}/${playbook}/cacert.pem
  tags:
  - ldap.cfg

- copy: src=${item} dest=/etc/pki/CA/certs/server-cert.crt owner=root group=root mode=0644
  first_available_file:
  - ${playbook_files_private}/${playbook}/server-cert.crt-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/server-cert.crt-${host_group}
  - ${playbook_files_private}/${playbook}/server-cert.crt-${datacentre}
  - ${playbook_files_private}/${playbook}/server-cert.crt
  - ${playbook_files}/${playbook}/server-cert.crt-${ansible_fqdn}
  - ${playbook_files}/${playbook}/server-cert.crt-${host_group}
  - ${playbook_files}/${playbook}/server-cert.crt-${datacentre}
  - ${playbook_files}/${playbook}/server-cert.crt
  tags:
  - ldap.cfg

- copy: src=${item} dest=/etc/pki/CA/certs/admin-cert.crt owner=root group=root mode=0644
  first_available_file:
  - ${playbook_files_private}/${playbook}/admin-cert.crt-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/admin-cert.crt-${host_group}
  - ${playbook_files_private}/${playbook}/admin-cert.crt-${datacentre}
  - ${playbook_files_private}/${playbook}/admin-cert.crt
  - ${playbook_files}/${playbook}/admin-cert.crt-${ansible_fqdn}
  - ${playbook_files}/${playbook}/admin-cert.crt-${host_group}
  - ${playbook_files}/${playbook}/admin-cert.crt-${datacentre}
  - ${playbook_files}/${playbook}/admin-cert.crt
  tags:
  - ldap.cfg

- template: src=${item} dest=/etc/sysconfig/dirsrv-admin owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${host_group}
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${datacentre}
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2
  tags:
  - ldap.cfg

- template: src=${item} dest=/root/setup-ds-admin.inf owner=root group=root mode=0400
  first_available_file:
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2-${host_group}
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2-${datacentre}
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2
  tags:
  - ldap.cfg

- shell: /usr/sbin/setup-ds-admin.pl --file=/root/setup-ds-admin.inf --silent creates=/etc/dirsrv/slapd-${ansible_hostname}/dse.ldif
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/slapd-${ansible_hostname} -A -n "CA certificate" -t CT,, -i /etc/openldap/cacerts/cacert.pem
  notify:
  - restart dirsrv
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/slapd-${ansible_hostname} -A -n "server-cert" -t CT,, -i /etc/pki/CA/certs/server-cert.crt
  notify:
  - restart dirsrv
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/admin-serv -A -n "CA certificate" -t CT,, -i /etc/openldap/cacerts/cacert.pem
  notify:
  - restart dirsrv-admin
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/admin-serv -A -n "admin-cert" -t CT,, -i /etc/pki/CA/certs/admin-cert.crt
  notify:
  - restart dirsrv-admin
  tags:
  - ldap.init

- template: src=${item} dest=/etc/dirsrv/slapd-${ansible_hostname}/pin.txt owner=${ldap389_sysUser} group=${ldap389_sysUser} mode=0400
  first_available_file:
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_slapd_pin.txt.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_slapd_pin.txt.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_slapd_pin.txt.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_slapd_pin.txt.j2
  - ${playbook_templates}/${playbook}/etc_dirsrv_slapd_pin.txt.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/etc_dirsrv_slapd_pin.txt.j2-${host_group}
  - ${playbook_templates}/${playbook}/etc_dirsrv_slapd_pin.txt.j2-${datacentre}
  - ${playbook_templates}/${playbook}/etc_dirsrv_slapd_pin.txt.j2
  notify:
  - restart dirsrv
  tags:
  - ldap.cfg

- template: src=${item} dest=/etc/dirsrv/admin-serv/password.conf owner=${ldap389_sysUser} group=${ldap389_sysUser} mode=0400
  first_available_file:
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_password.conf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_password.conf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_password.conf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_password.conf.txt.j2
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_password.conf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_password.conf.j2-${host_group}
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_password.conf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_password.conf.j2
  notify:
  - restart dirsrv-admin
  tags:
  - ldap.cfg

- template: src=${item} dest=/etc/dirsrv/admin-serv/nss.conf owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_nss.conf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_nss.conf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_nss.conf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/etc_dirsrv_admin-serv_nss.conf.txt.j2
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_nss.conf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_nss.conf.j2-${host_group}
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_nss.conf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/etc_dirsrv_admin-serv_nss.conf.j2
  notify:
  - restart dirsrv-admin
  tags:
  - ldap.cfg

- service: name=dirsrv enabled=yes state=started
  tags:
  - ldap.srv

- service: name=dirsrv-admin enabled=yes state=started
  tags:
  - ldap.srv
