#
# LDAP 389 Directory Server Tasks
#
---
- yum: pkg=${item} state=installed
  with_items:
  - 389-ds
  - bind-utils
  tags:
  - ldap.pkgs

# manage tree structure
#- copy: src=${item} dest=/etc/httpd owner=root group=root mode=0600
#  with_fileglob:
#  - ${playbook_files_private}/${playbook}/${ansible_fqdn}/*
#  - ${playbook_files_private}/${playbook}/${host_group}/*
#  - ${playbook_files_private}/${playbook}/${datacentre}/*
#  - ${playbook_files_private}/${playbook}/default/*
#  - ${playbook_files}/${playbook}/${ansible_fqdn}/*
#  - ${playbook_files}/${playbook}/${host_group}/*
#  - ${playbook_files}/${playbook}/${datacentre}/*
#  - ${playbook_files}/${playbook}/default/*
#  notify:
#  - restart template
#  tags:
#  - template.cfg
#  - template
#  - cfg

- copy: src=${item} dest=/etc/openldap/cacerts/cacert.pem owner=root group=root mode=0644
  first_available_file:
  - ${playbook_files_private}/${playbook}/cacert.pem-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/cacert.pem-${host_group}
  - ${playbook_files_private}/${playbook}/cacert.pem-${datacentre}
  - ${playbook_files_private}/${playbook}/cacert.pem
  - ${playbook_files}/${playbook}/cacert.pem-${ansible_fqdn}
  - ${playbook_files}/${playbook}/cacert.pem-${host_group}
  - ${playbook_files}/${playbook}/cacert.pem-${datacentre}
  - ${playbook_files}/${playbook}/cacert.pem
  tags:
  - ldap.cfg

- copy: src=${item} dest=/etc/ansible/utils/pki/CA/certs/server-cert.crt owner=root group=root mode=0644
  first_available_file:
  - ${playbook_files_private}/${playbook}/server-cert.crt-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/server-cert.crt-${host_group}
  - ${playbook_files_private}/${playbook}/server-cert.crt-${datacentre}
  - ${playbook_files_private}/${playbook}/server-cert.crt
  - ${playbook_files}/${playbook}/server-cert.crt-${ansible_fqdn}
  - ${playbook_files}/${playbook}/server-cert.crt-${host_group}
  - ${playbook_files}/${playbook}/server-cert.crt-${datacentre}
  - ${playbook_files}/${playbook}/server-cert.crt
  tags:
  - ldap.cfg

- copy: src=${item} dest=/etc/ansible/utils/pki/CA/certs/admin-cert.crt owner=root group=root mode=0644
  first_available_file:
  - ${playbook_files_private}/${playbook}/admin-cert.crt-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/admin-cert.crt-${host_group}
  - ${playbook_files_private}/${playbook}/admin-cert.crt-${datacentre}
  - ${playbook_files_private}/${playbook}/admin-cert.crt
  - ${playbook_files}/${playbook}/admin-cert.crt-${ansible_fqdn}
  - ${playbook_files}/${playbook}/admin-cert.crt-${host_group}
  - ${playbook_files}/${playbook}/admin-cert.crt-${datacentre}
  - ${playbook_files}/${playbook}/admin-cert.crt
  tags:
  - ldap.cfg

- template: src=${item} dest=/etc/sysconfig/dirsrv-admin owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/etc_sysconfig_dirsrv-admin.j2
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${host_group}
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2-${datacentre}
  - ${playbook_templates}/${playbook}/etc_sysconfig_dirsrv-admin.j2
  tags:
  - ldap.cfg

- template: src=${item} dest=/root/.setup-ds-admin.inf owner=root group=root mode=0400
  first_available_file:
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/root_setup_ds_admin.j2
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2-${host_group}
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2-${datacentre}
  - ${playbook_templates}/${playbook}/root_setup_ds_admin.j2
  tags:
  - ldap.cfg

- shell: /usr/sbin/setup-ds-admin.pl --file=/root/.setup-ds-admin.inf --silent creates=/etc/dirsrv/slapd-${ansible_hostname}/dse.ldif
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/slapd-${ansible_hostname} -A -n "CA certificate" -t CT,, -i /etc/openldap/cacerts/cacert.pem
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/slapd-${ansible_hostname} -A -n "server-cert" -t CT,, -i /etc/ansible/utils/pki/CA/certs/server-cert.crt
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/admin-serv -A -n "CA certificate" -t CT,, -i /etc/openldap/cacerts/cacert.pem
  tags:
  - ldap.init

- shell: /usr/bin/certutil -d /etc/dirsrv/admin-serv -A -n "admin-cert" -t CT,, -i /etc/ansible/utils/pki/CA/certs/admin-cert.crt
  tags:
  - ldap.init

# manage service
#- service: name=templated enabled=yes state=started
#  tags:
#  - templated.srv
