#
# Logrotate Tasks
#
---
- template: dest=/etc/logrotate.conf
  first_available_file:
  - ${playbook_templates_private}/${playbook}/logrotate.conf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/logrotate.conf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/logrotate.conf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/logrotate.conf.j2
  - ${playbook_templates}/${playbook}/logrotate.conf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/logrotate.conf.j2-${host_group}
  - ${playbook_templates}/${playbook}/logrotate.conf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/logrotate.conf.j2
  tags:
  - logrotate.cfg

# TODO: possible bugs
# src has to be included here. broken shorthand. 
# host_group needs to be defined in host_vars/$fqdn
- copy: src=${item} dest=/etc/logrotate.d/
  with_fileglob:
  - ${playbook_files_private}/${playbook}/${ansible_fqdn}/*
  - ${playbook_files_private}/${playbook}/${host_group}/*
  - ${playbook_files_private}/${playbook}/${datacentre}/*
  - ${playbook_files_private}/${playbook}/logrotate.d/*
  - ${playbook_files}/${playbook}/${ansible_fqdn}/*
  - ${playbook_files}/${playbook}/${host_group}/*
  - ${playbook_files}/${playbook}/${datacentre}/*
  - ${playbook_files}/${playbook}/logrotate.d/*
  tags:
  - logrotate.d
