#
# Maven Tasks
#
---
- file: dest=${maven_m2} state=directory owner=${maven_user} group=${maven_group} mode=0755
  tags:
  - maven.init

- template: src=${item} dest=${maven_m2}/settings.xml owner=${maven_user} group=${maven_group} mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/settings.xml.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/settings.xml.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/settings.xml.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/settings.xml.j2
  - ${playbook_templates}/${playbook}/settings.xml.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/settings.xml.j2-${host_group}
  - ${playbook_templates}/${playbook}/settings.xml.j2-${datacentre}
  - ${playbook_templates}/${playbook}/settings.xml.j2
  tags:
  - maven.cfg
