#
# Nexus Tasks
#
---
- file: dest=${nexus_m2} state=directory owner=${nexus_user} group=${nexus_group} mode=0755
  tags:
  - nexus.init

- template: src=${item} dest=${nexus_m2}/settings.xml owner=${nexus_user} group=${nexus_group} mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/settings.xml.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/settings.xml.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/settings.xml.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/settings.xml.j2
  - ${playbook_templates}/${playbook}/settings.xml.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/settings.xml.j2-${host_group}
  - ${playbook_templates}/${playbook}/settings.xml.j2-${datacentre}
  - ${playbook_templates}/${playbook}/settings.xml.j2
  tags:
  - nexus.cfg
