#
# Ntp Tasks
#
---
- yum: pkg=${item} state=installed
  with_items:
  - ntp
  tags:
  - ntp.pkgs

- copy: src=${item} dest=/etc/ntp/
  with_fileglob:
  - ${playbook_files_private}/${playbook}/${ansible_fqdn}/*
  - ${playbook_files_private}/${playbook}/${host_group}/*
  - ${playbook_files_private}/${playbook}/${datacentre}/*
  - ${playbook_files_private}/${playbook}/etc_ntp/*
  - ${playbook_files}/${playbook}/${ansible_fqdn}/*
  - ${playbook_files}/${playbook}/${host_group}/*
  - ${playbook_files}/${playbook}/${datacentre}/*
  - ${playbook_files}/${playbook}/etc_ntp/*
  notify:
  - restart ntpd
  tags:
  - ntpd.cfg
  - ntpd
  - cfg

- template: src=${item} dest=/etc/ntp.conf owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/ntp.conf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/ntp.conf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/ntp.conf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/ntp.conf.j2
  - ${playbook_templates}/${playbook}/ntp.conf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/ntp.conf.j2-${host_group}
  - ${playbook_templates}/${playbook}/ntp.conf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/ntp.conf.j2
  notify:
  - restart ntpd
  tags:
  - ntp.cfg
  - ntpd
  - cfg

- service: name=ntpd enabled=yes state=started
  tags:
  - ntp.srv
