#
# Php Tasks
#
---
# TODO: externalize this list
- yum: pkg=${item} state=installed
  ignore_errors: yes
  with_items:
  - php-soap
  - php-mysql
  - php-xml
  - phpmyadmin
  tags:
  - php.pkgs

- template: dest=/etc/php.ini owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/php.ini.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/php.ini.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/php.ini.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/php.ini.j2
  - ${playbook_templates}/${playbook}/php.ini.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/php.ini.j2-${host_group}
  - ${playbook_templates}/${playbook}/php.ini.j2-${datacentre}
  - ${playbook_templates}/${playbook}/php.ini.j2
  notify:
  - restart httpd
  tags:
  - php.cfg

# TODO: place holder to manage phpmyadmin configs
