#
# Properties Tasks
#
---
- file: dest=${properties_dir} state=directory mode=0770
  when_set: ${properties_dir}
  tags:
  - properties.cfg
  - properties
  - cfg

- copy: src=${item} dest=${properties_dir} owner=root group=root mode=0640
  when_set: ${properties_dir}
  with_fileglob:
  - ${playbook_files_private}/${playbook}/${ansible_fqdn}/*
  - ${playbook_files_private}/${playbook}/${host_group}/*
  - ${playbook_files_private}/${playbook}/${datacentre}/*
  - ${playbook_files_private}/${playbook}/default/*
  - ${playbook_files}/${playbook}/${ansible_fqdn}/*
  - ${playbook_files}/${playbook}/${host_group}/*
  - ${playbook_files}/${playbook}/${datacentre}/*
  - ${playbook_files}/${playbook}/default/*
  tags:
  - properties.cfg
  - properties
  - cfg
