#
# Repos Tasks
#
---
#- yum: pkg=${item} state=installed
#  with_items:
#  - pkg1
#  - pkg2
#  tags:
#  - template.pkgs

- copy: src=${item} dest=/etc/yum.repos.d owner=root group=root mode=0644
  with_fileglob:
  - ${playbook_files_private}/${playbook}/${ansible_fqdn}/${ansible_lsb.id}${ansible_lsb.major_release}/*
  - ${playbook_files_private}/${playbook}/${host_group}/${ansible_lsb.id}${ansible_lsb.major_release}/*
  - ${playbook_files_private}/${playbook}/${datacentre}/${ansible_lsb.id}${ansible_lsb.major_release}/*
  - ${playbook_files_private}/${playbook}/default/${ansible_lsb.id}${ansible_lsb.major_release}/*
  - ${playbook_files}/${playbook}/${ansible_fqdn}/${ansible_lsb.id}${ansible_lsb.major_release}/*
  - ${playbook_files}/${playbook}/${host_group}/${ansible_lsb.id}${ansible_lsb.major_release}/*
  - ${playbook_files}/${playbook}/${datacentre}/${ansible_lsb.id}${ansible_lsb.major_release}/*
  - ${playbook_files}/${playbook}/default/${ansible_lsb.id}${ansible_lsb.major_release}/*
  ignore_errors: yes
  tags:
  - repos.cfg
  - repos
  - cfg

# manage static configs
#- copy: src=${item} dest=/etc/template.cnf owner=root group=root mode=0600
#  first_available_file:
#  - ${playbook_files_private}/${playbook}/template.cnf-${ansible_fqdn}
#  - ${playbook_files_private}/${playbook}/template.cnf-${host_group}
#  - ${playbook_files_private}/${playbook}/template.cnf-${datacentre}
#  - ${playbook_files_private}/${playbook}/template.cnf
#  - ${playbook_files}/${playbook}/template.cnf-${ansible_fqdn}
#  - ${playbook_files}/${playbook}/template.cnf-${host_group}
#  - ${playbook_files}/${playbook}/template.cnf-${datacentre}
#  - ${playbook_files}/${playbook}/template.cnf
#  notify:
#  - restart template
#  tags:
#  - template.cfg

# manage dynamic configs
#- template: src=${item} dest=/etc/template.cnf owner=root group=root mode=0600
#  first_available_file:
#  - ${playbook_templates_private}/${playbook}/template.cnf.j2-${ansible_fqdn}
#  - ${playbook_templates_private}/${playbook}/template.cnf.j2-${host_group}
#  - ${playbook_templates_private}/${playbook}/template.cnf.j2-${datacentre}
#  - ${playbook_templates_private}/${playbook}/template.cnf.j2
#  - ${playbook_templates}/${playbook}/template.cnf.j2-${ansible_fqdn}
#  - ${playbook_templates}/${playbook}/template.cnf.j2-${host_group}
#  - ${playbook_templates}/${playbook}/template.cnf.j2-${datacentre}
#  - ${playbook_templates}/${playbook}/template.cnf.j2
#  tags:
#  - template.cfg

# manage service
#- service: name=templated enabled=yes state=started
#  tags:
#  - templated.srv
