#
# Root Tasks
#
---
- user: name=root password=${root_passwd} state=present
  when_set: ${root_passwd}
  tags:
  - root.passwd

- template: src=${item} dest=/root/.bashrc owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/bashrc.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/bashrc.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/bashrc.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/bashrc.j2
  - ${playbook_templates}/${playbook}/bashrc.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/bashrc.j2-${host_group}
  - ${playbook_templates}/${playbook}/bashrc.j2-${datacentre}
  - ${playbook_templates}/${playbook}/bashrc.j2
  tags:
  - root.bashrc

- template: src=${item} dest=/root/.bash_profile owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/bash_profile.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/bash_profile.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/bash_profile.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/bash_profile.j2
  - ${playbook_templates}/${playbook}/bash_profile.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/bash_profile.j2-${host_group}
  - ${playbook_templates}/${playbook}/bash_profile.j2-${datacentre}
  - ${playbook_templates}/${playbook}/bash_profile.j2
  tags:
  - root.bashrc

- template: src=${item} dest=/root/.bash_logout owner=root group=root mode=0644
  first_available_file:
  - ${playbook_templates_private}/${playbook}/bash_logout.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/bash_logout.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/bash_logout.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/bash_logout.j2
  - ${playbook_templates}/${playbook}/bash_logout.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/bash_logout.j2-${host_group}
  - ${playbook_templates}/${playbook}/bash_logout.j2-${datacentre}
  - ${playbook_templates}/${playbook}/bash_logout.j2
  tags:
  - root.bashrc
