#
# Sudoers Tasks
#
---
- template: src=${item} dest=/etc/sudoers owner=root group=root mode=0440
  first_available_file:
  - ${playbook_templates_private}/${playbook}/sudoers.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/sudoers.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/sudoers.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/sudoers.j2
  - ${playbook_templates}/${playbook}/sudoers.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/sudoers.j2-${host_group}
  - ${playbook_templates}/${playbook}/sudoers.j2-${datacentre}
  - ${playbook_templates}/${playbook}/sudoers.j2
  tags:
  - sudoers.cfg
  - sudoers
  - cfg
