#
# Sysctl Tasks
#
---
- copy: dest=/etc/sysctl.conf owner=root group=root mode=0644
  first_available_file:
  - ${playbook_files_private}/${playbook}/sysctl.conf-optimized-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/sysctl.conf-optimized-${host_group}
  - ${playbook_files_private}/${playbook}/sysctl.conf-optimized-${datacentre}
  - ${playbook_files_private}/${playbook}/sysctl.conf-optimized
  - ${playbook_files}/${playbook}/sysctl.conf-optimized-${ansible_fqdn}
  - ${playbook_files}/${playbook}/sysctl.conf-optimized-${host_group}
  - ${playbook_files}/${playbook}/sysctl.conf-optimized-${datacentre}
  - ${playbook_files}/${playbook}/sysctl.conf-optimized
  notify:
  - restart sysctl
  tags:
  - sysctl.config
