#
# REFERENCE: tasks
#
---
- yum: pkg=${item} state=installed
  with_items:
  - mysql-server
  - MySQL-python
  tags:
  - mysql.pkgs

- copy: dest=/etc/httpd state=preset
  with_fileglob:
  - ${playbook_files}/${playbook}/*
  notify:
  - restart httpd
  tags:
  - httpd.cfg
  - httpd
  - cfg

- copy: dest=/etc/my.cnf
  first_available_file:
  - ${playbook_files_private}/${playbook}/my.cnf-${ansible_fqdn}
  - ${playbook_files_private}/${playbook}/my.cnf-${host_group}
  - ${playbook_files_private}/${playbook}/my.cnf-${datacentre}
  - ${playbook_files_private}/${playbook}/my.cnf
  - ${playbook_files}/${playbook}/my.cnf-${ansible_fqdn}
  - ${playbook_files}/${playbook}/my.cnf-${host_group}
  - ${playbook_files}/${playbook}/my.cnf-${datacentre}
  - ${playbook_files}/${playbook}/my.cnf
  notify:
  - restart mysqld
  tags:
  - mysql.cfg

- template: dest=/root/.my.cnf
  first_available_file:
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/user.my.cnf.j2
  - ${playbook_templates}/${playbook}/user.my.cnf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/user.my.cnf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/user.my.cnf.j2-${host_group}
  - ${playbook_templates}/${playbook}/user.my.cnf.j2
  tags:
  - mysql.cfg

