#
# Ulimit Playbook
#
---
- name: Ulimit Playbook
  hosts: all

  vars_files:
  - ../global/vars/main.yml
  - ${playbook_vars_default}
  - ${playbooks_extension}/${playbook}/${playbook_vars_default}

  tasks:
  - include: ${playbook_tasks_default}

  #handlers:
  #- include: ${playbook_handlers_default}
